[package]
name = "cross-margin-public"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "*", features = ["derive"]}
cross-calculations = { git = "https://github.com/my-cfd-platform/cross-calculations.git", tag = "0.1.4" }